##############################################################################
#
#    file                 : Makefile
#    created              : Wed Jan 19 19:07:05 CET 2000
#    copyright            : (C) 1999 by Eric Espie                         
#    email                : torcs@free.fr   
#    version              : $Id: Makefile,v 1.9 2008/02/24 16:44:51 berniw Exp $                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################

TRACK     = alpine-1

DATADIR   = tracks/road/alpine-1

DATA      = $(TRACK).xml $(TRACK).acc $(TRACK).png arbor01.rgb asgrassr_n.rgb barg3.rgb \
			cham2.rgb concdal.rgb gconcrete.rgb ggrass3.rgb house.rgb mur2.rgb murpub.rgb \
			poutre3.rgb readme.txt road1.rgb road4.rgb rockg0.rgb torcs2.rgb treeg10.rgb \
			truck0.rgb truck1.rgb walls.rgb walls2.rgb background.png shadow2.rgb

data-tracks-road_PKGFILES	= $(DATA)

data-tracks-road_PKGDIR		= $(DATADIR)

include ${MAKE_DEFAULT}


