##############################################################################
#
#    file                 : Makefile
#    created              : Wed Jan 19 19:07:05 CET 2000
#    copyright            : (C) 1999-2005 by Eric Espie, Bernhard Wymann
#    email                : torcs@free.fr
#    version              : $Id: Makefile,v 1.10 2005/05/27 13:55:16 berniw Exp $                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################


DATADIR   = tracks/road/g-track-2

DATA      = g-track-2.xml g-track-2.acc g-track-2.png background.png readme.txt alltree.rgb arbor01.rgb \
			gconcrete.rgb poutre3_arbor_n.rgb concdal.rgb \
			asp_n.rgb asphalt4.rgb asphalt.rgb barr1.rgb spec.rgb torcs1.rgb poutre4.rgb tent.rgb \
			barg2.rgb torcs2.rgb std.rgb asconcr.rgb trcurbr.rgb trcurbl.rgb barg3.rgb rock4.rgb \
			gtirewall.rgb gsand.rgb treewate.rgb torcs0_arbor_n.rgb grassg1.rgb \
			grassg3.rgb shadow2.rgb

data-tracks-road_PKGFILES	= $(DATA)

data-tracks-road_PKGDIR	= $(DATADIR)

include ${MAKE_DEFAULT}


