##############################################################################
#
#    file                 : Makefile
#    created              : Sun Mar 19 00:18:15 CET 2000
#    copyright            : (C) 2000, 2006 by Eric Espie, Bernhard Wymann
#    email                : berniw@bluewin.ch
#    version              : $Id: Makefile,v 1.1 2006/10/04 01:45:52 berniw Exp $
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################


DATADIR   = tracks/oval/michigan

DATA      = michigan.xml background.png michigan.acc michigan.png readme.txt \
			allborg-trees_n.rgb arbor_frame_n.rgb asphalt-bw-m1-1_n.rgb \
			asphalt-bw-m1-pit-1_n.rgb asphalt-bw-m1-pitentry-1_n.rgb \
			asphalt-bw-m1-pitentry-leftside-1_n.rgb block1.rgb block2.rgb border-dirt.rgb \
			facade4-512.rgb forest1-tree-m1_n.rgb grass-m1-2.rgb grass-m1.rgb grass-m3-arbor_n.rgb \
			michigan-arbor_n.rgb poutre3_arbor_n.rgb roof3.rgb roof5.rgb std.rgb tarmac-wall-2-g2.rgb \
			tent.rgb torcs0_arbor_n.rgb torcs1.rgb torcs-url-yellow-red.rgb truck_arbor_berniw_n.rgb \
			truck_arbor_bt_n.rgb truck_arbor_ctd_n.rgb truck_arbor_cylos_n.rgb truck_arbor_inferno_n.rgb \
			truck_arbor_speedy_n.rgb truck_arbor_tanhoj_n.rgb truck_arbor_tita_n.rgb wall4.rgb \
			wall-m1-2.rgb wall-m1.rgb wall-torcs.rgb shadow2.rgb


data-tracks-oval_PKGFILES	= $(DATA)

data-tracks-oval_PKGDIR		= $(DATADIR)

include ${MAKE_DEFAULT}


