.TH "TORCS" "6" "1.1" "Rudy Godoy" "Games"
.SH "NAME"
.LP
nfs2ac
.SH "DESCRIPTION"
.TP
This manual describes the nfs2ac application that is shipped with the game TORCS.
This is a holder manpage.
.SH "OPTIONS"
.TP
This program does not use arguments.
.SH "SEE ALSO"
.BR torcs (6)
.SH "AUTHOR"
.LP
This manual page was writen by Rudy Godoy <rudy@kernel-panik.org>,
for the Debian GNU/Linux system (but may be used by others).

