.TH "Car Specifications Converter" "6" "1.1" "Rudy Godoy" "Games"
.SH "NAME"
.LP
nfsperf \- Car Specifications Converter
.SH "SYNTAX"
.LP
nfsperf [-c category.xml] [-i <input carp.txt>] [-o output carp.xml]
.SH "DESCRIPTION"
.TP
This manual describes the Car Specifications Converter application that is shipped with the game TORCS.
.SH "OPTIONS"
.TP
.B -c \fIcategory.xml\fP
car category description
.TP
.B -i \fIinput carp.txt\fP
input NFS carp.txt
.TP
.B -o \fIoutput carp.xml\fP
converted parameters
.SH "SEE ALSO"
.BR torcs (6)
.SH "AUTHOR"
.LP
This manual page was writen by Rudy Godoy <rudy@kernel-panik.org>,
for the Debian GNU/Linux system (but may be used by others).

