.TH "Texture Auto Mapper" "6" "1.1" "Rudy Godoy" "Games"
.SH "NAME"
.LP
texmapper \- Texture Auto Mapper
.SH "SYNTAX"
.LP
texmapper [options]
.SH "DESCRIPTION"
.TP
This manual describes the use of Texture Auto Mapper application that is shipped with TORCS game.
.SH "OPTIONS"
.TP
.B -f \fI<input acfile>\fP
input model file in AC3D format [car.ac]
.TP
.B -o \fI<output acfile>\fP
ouput model file in AC3D format [car-out.ac]
.TP
.B -p \fI<parameters>\fP
parameters in XML format [texmapper.xml]
.TP
.B -s \fI<file>\fP
output skin file [skin.rgb]
.TP
.B --help
print this message
.SH "SEE ALSO"
.BR torcs (6)
.SH "AUTHOR"
.LP
This manual page was writen by Rudy Godoy <rudy@kernel-panik.org>,
for the Debian GNU/Linux system (but may be used by others).
