.TH "TORCS" "6" "1.2.2" "Rudy Godoy" "Games"
.SH NAME
torcs \- 3D racing cars simulator game using OpenGL
.SH DESCRIPTION
TORCS, The Open Racing Car Simulator, is a car racing simulation, which
allows you to drive in races against opponents simulated by the computer.
You can also develop your own computer-controlled driver (also called a
robot) in C or C++.
.br
TORCS is "Open Source" (GNU General Public License Version 2 or later).
.SH OPTIONS
This program doesn't have any option.
.SH SEE ALSO
For a more detailed player manual, please see:
.br
http://torcs.sourceforge.net/sections.php?op=viewarticle&artid=10
.SH AUTHOR
This manual page was written by Rudy Godoy <rudy@kernel-panik.org>,
for the Debian project (but may be used by others).
