.TH "TORCS" "6" "1.2.2" "Rudy Godoy" "Games"
.SH NOMBRE
torcs \- Juego 3D simulador de carrera de autos usando OpenGL
.SH DESCRIPCIÓN
TORCS, El simulador de carrera de autos, es una simulación de carrera de
autos que le permite manejar en carreras contra oponentes simulados por
la computadora. Usted también puede construir sus propios conductores
contolados por computadora (también llamados robots) en C o C++.
.br
TORCS es un programa de "código abierto" licenciado bajo la GNU General
Public License Version 2 o posterior.
.SH OPCIONES
This program doesn't have any option.
.SH VÉASE TAMBIÉN
Para un manual mas detallado sobre como jugar, por favor véa: 
.br
http://torcs.sourceforge.net/sections.php?op=viewarticle&artid=10
.SH AUTOR
Esta página de manual ha sido escrita por Rudy Godoy <rudy@kernel-panik.org>,
para el proyecto Debian (pero puede ser usada por otros).
