##############################################################################
#
#    file                 : Makefile
#    created              : Sun Feb 13 17:25:53 CET 2000
#    copyright            : (C) 2000 by Eric Espie                         
#    email                : torcs@free.fr   
#    version              : $Id: Makefile,v 1.3 2005/06/08 09:08:55 berniw Exp $                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################

TRACK	  = ole-road-1

CATEGORY  = road

DATADIR   = tracks/$(CATEGORY)/$(TRACK)

DATA      = $(TRACK).xml $(TRACK).acc $(TRACK).png concrete-patch.png cracked-asphalt.png \
			ole-concrete-pits.png ole-concrete-side.png patched-asphalt-1.png \
			patched-asphalt-2.png readme.txt shadow2.rgb tr-asphalt-l_nmm.rgb close-bush.rgb \
			background.png

data-tracks-road_PKGFILES	= $(DATA)

data-tracks-road_PKGDIR		= $(DATADIR)

include ${MAKE_DEFAULT}


