##############################################################################
#
#    file                 : Makefile
#    created              : Mon Mai 30 01:20:21 CET 2006
#    copyright            : (C) 2006 by Bernhard Wymann
#    email                : berniw@bluewin.ch
#    version              : $Id: Makefile,v 1.2 2008/02/24 16:19:02 berniw Exp $
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################

TRACK     = dirt-3

DATADIR   = tracks/dirt/$(TRACK)

DATA      = $(TRACK).xml $(TRACK).acc $(TRACK).png readme.txt background.png ambush-inn.png \
			dirt-grass.png sign-left_n.png dirt-pits.png sign-pit_n.png barrier-fence_n.png \
			dirt-side.png stone1.png barrier-rusty.png grass-clump-arbor_n.png tank.png \
			barrier-wooden_n.png hat.png tree_bush2_arbor_n.png black.png newdirt2.png \
			tree_gum2_arbor_n.png bridgeplanks.png newdirt.png tree_gum_arbor_n.png \
			cabin.png newgrass.png tr-house-arbor_n.png pit-walls.png poutre2_arbor_n.rgb \
			poutre3_arbor_n.rgb shadow2.rgb dirt-grass2.png shadow2.png shadow3.png \
			advert-cola.png advert-joes.png advert-ols.png

data-tracks-dirt_PKGFILES	= $(DATA)

data-tracks-dirt_PKGDIR	= $(DATADIR)

include ${MAKE_DEFAULT}


