##############################################################################
#
#    file                 : Makefile
#    created              : Wed Jan 19 19:07:05 CET 2000
#    copyright            : (C) 1999 by Eric Espie                         
#    email                : torcs@free.fr   
#    version              : $Id: Makefile,v 1.4 2005/06/08 09:46:00 berniw Exp $                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################

TRACK     = g-track-3

DATADIR   = tracks/road/g-track-3

DATA      = $(TRACK).xml $(TRACK).acc $(TRACK).png arbor-wood_n.rgb arbor01.rgb asasphr.rgb \
			asconcr.rgb asgrassr_n.rgb asp_n.rgb asphalt4.rgb assandr.rgb barg2.rgb barg3.rgb \
			concdal.rgb gconcrete.rgb ggrass3.rgb gsand.rgb gtirewall.rgb house.rgb \
			mur2.rgb road1.rgb road2.rgb road3.rgb road4.rgb road5.rgb rockg0.rgb torcs1.rgb \
			torcs2.rgb treebui1.rgb treeg10.rgb truck0.rgb truck1.rgb walls.rgb walls2.rgb \
			readme.txt background.png shadow2.rgb skid_m2.rgb 

data-tracks-road_PKGFILES	= $(DATA)

data-tracks-road_PKGDIR	= $(DATADIR)

include ${MAKE_DEFAULT}


