##############################################################################
#
#    file                 : Makefile
#    created              : Sun Feb 13 17:43:26 CET 2000
#    copyright            : (C) 2000-2005 by Eric Espie, Bernhard Wymann                         
#    email                : torcs@free.fr   
#    version              : $Id: Makefile,v 1.8 2005/03/09 19:50:28 berniw Exp $                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################


DATADIR   = tracks/road/e-track-1

DATA      = e-track-1.xml background.png e-track-1.acc e-track-1.png readme.txt geo-bw1.rgb \
			shadow2.rgb tr-barrier-bw.rgb tr-curb-bw-l.rgb tr-curb-bw-r.rgb tr-grass-bw1.rgb \
			tr-grass-bw2.rgb tr-asphalt-bw3-pit-e_n.rgb tr-asphalt-bw3-pit-l_n.rgb \
			tr-asphalt-bw3-pit_n.rgb tr-asphalt-bw3_n.rgb


data-tracks-road_PKGFILES	= $(DATA)

data-tracks-road_PKGDIR		= $(DATADIR)

include ${MAKE_DEFAULT}


