##############################################################################
#
#    file                 : Makefile
#    created              : Sun Mar 12 16:19:53 CET 2000
#    copyright            : (C) 2000 by Eric Espie                         
#    email                : torcs@free.fr   
#    version              : $Id: Makefile,v 1.1.2.1 2008/11/23 16:33:15 berniw Exp $                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################

DATADIR   = tracks/dirt/dirt-1

DATA      = dirt-1.xml dirt-1.acc dirt-1.png readme.txt \
			background.png castle-arbor_n.rgb concrete_white.rgb pylon3.rgb pylon-arbor_n.rgb \
			rock3.rgb shadow2.rgb tr-barrier-curve.rgb tr-barrier.rgb tr-barrier-start.rgb \
			tr-dirtb.rgb tr-dirt.rgb tree13_n.rgb \
			tree15_n.rgb tree16_n.rgb tree17_n.rgb tree1_n.rgb tree2_n.rgb \
			tree3_n.rgb tree4_n.rgb tree5_n.rgb tree7_n.rgb tree8_n.rgb \
			tree9_n.rgb tr-grass.rgb waterplants-arbor_n.rgb water.rgb

data-tracks-dirt_PKGFILES	= $(DATA)

data-tracks-dirt_PKGDIR		= $(DATADIR)

include ${MAKE_DEFAULT}


