##############################################################################
#
#    file                 : Makefile
#    created              : Sun Apr 30 15:45:24 CEST 2000
#    copyright            : (C) 2000 by Eric Espie                         
#    email                : torcs@free.fr   
#    version              : $Id: Makefile,v 1.1 2008/02/24 15:23:59 berniw Exp $                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################


DATADIR   = tracks/road/e-track-6

DATA      = e-track-6.xml e-track-6.acc readme.txt \
			01.png 02.png ALAUBM.png armco.png background.png BLBDBK.png BRDGA.png \
			BRDGB.png BRIQUE.png BUS.png CAMPER01.png CAMPER02.png CAMPER3.png CAMPER41.png \
			CAMPER4.png CAR01.png CAR02.png CAR03.png CAR04.png CAR05.png CAR06.png CAR07.png \
			CAR08.png CHtree_n.png cliff2.png CMNTA.png CMNTBB.png CMNTB.png conc.png \
			CONCSH01.png CONCTP.png CRNA.png CRNB.png CRNC.png CRND.png CRNF.png DIST01.png \
			DIST03.png DIST04.png e-track-6.png F3BASE.png FENCWIRE_arbor_n.png FNCEB.png \
			GBtree_n.png GEtree_n.png grass3.png GRASSAND.png GRASS.png GSPAtree.png \
			GSTNDA.png H15FRNT.png H15RF.png H15SFRNT.png H15SIDE1.png H15SIDE2.png \
			H15SIDE3.png H17F1.png H17F2.png H17F3.png H17F4.png H17F5.png H17F6.png \
			H17FA.png H17FB.png H17FNT.png H17SID.png H17TOP.png H21F1.png H21F2.png \
			H21F3.png H21F4.png H21F5.png H21F6.png H21FA.png H21FB.png H21FNT.png H21SID.png \
			H21TOP.png H25RF.png H26F1.png H26F2.png H26F3.png H26F4.png H26F5.png H26F6.png \
			H26FA.png H26FB.png H26FNT.png H26SID.png H26TOP.png H28FRNT.png IYtree_n.png \
			LAMAOP.png LOGOAG2.png LOGOAG.png LOGOAT.png LOGODUN2.png LOGOFSTN.png LOGOGFLG.png \
			LOGOMBIL.png LOGOPANA.png LOGOSUIS.png LOGOTSUB.png M40A.png MASE01.png MASE02.png \
			MOB1DUO.png MUR43A.png MUR43B.png OBJA24_arbor_n.png PDKKA13.png PITWB.png \
			RA4BRIG5.png RDGRTRAN.png ROAD2_n.png ROADC.png roadgras.png roadgrsd.png \
			ROAD_n.png ROADPARK.png ROADPE_n.png ROADPL_n.png ROADPT_n.png roadsand.png \
			rroadgrs.png RSA02.png S463ET.png S46POR.png SAND02.png SEMA02.png shadow2.png \
			shadow3.png STAIRSD.png STAIRS.png TENTG.png TENTH.png TOITCAS.png TOPCROWD.png \
			tree_apple_n.png tree_bush_n.png treefc_n.png tree-fir_n.png treeline_n.png \
			tree_maple_n.png tree-pine1_n.png TreeRNS3.png TreeRNS4.png TreeRNS5.png \
			treeUGLIES01_n.png treeUGLIES02_n.png treeUGLIES04_n.png TRIBA07_arbor_n.png \
			TRIBA08.png TRIBA09_arbor_n.png TRIBA11.png TRIBB01.png TRIBB02.png TRIBB03.png \
			wall2.png WHEEL.png WHEELS6.png ZBRID.png ZPIT3.png ZPIT.png block1.rgb \
			concrete2.rgb concrete.rgb pylon1.rgb shadow2.rgb torcsad1.rgb torcsad2.rgb

data-tracks-road_PKGFILES	= $(DATA)

data-tracks-road_PKGDIR		= $(DATADIR)

include ${MAKE_DEFAULT}


