##############################################################################
#
#    file                 : Makefile
#    created              : Sat Mai 20 17:12:55 CET 2006
#    copyright            : (C) 2006 by Bernhard Wymann
#    email                : berniw@bluewin.ch
#    version              : $Id: Makefile,v 1.1 2008/02/24 14:24:44 berniw Exp $
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################

TRACK     = wheel-2

DATADIR   = tracks/road/$(TRACK)

DATA      = $(TRACK).xml $(TRACK).acc $(TRACK).png readme.txt \
			asphalt_mr-pitentry_n.png asphalt_n.png asphalt-pit_n.png asphalt-sidel_n.png \
			background.png building1.png building2.png clkdtm.png girder_tree_n.png grass.png \
			rmbl.png sand.png sbridge2.png shadow2.png sign1.png sign2.png sign3.png swall2.png \
			tirewall.png tr-barrier.png tr-barrier-tree_n.png treeg11_n.png treeline.png \
			tree_n.png tr-spec.png truck_arbor_ctd_n.png water_green2.png wheel-2.png wheel.png \
			barr1_n.rgb concdal.rgb shadow2.rgb texwheel.rgb torcs1.rgb truck0.rgb


data-tracks-road_PKGFILES	= $(DATA)

data-tracks-road_PKGDIR	= $(DATADIR)

include ${MAKE_DEFAULT}


