##############################################################################
#
#    file                 : Makefile
#    created              : Wed Jan 19 19:07:05 CET 2000
#    copyright            : (C) 1999 by Eric Espie 
#    email                : torcs@free.fr
#    version              : $Id: Makefile,v 1.1 2006/05/28 21:05:27 berniw Exp $
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################

TRACK     = street-1

DATADIR   = tracks/road/street-1

DATA      = $(TRACK).xml $(TRACK).acc $(TRACK).png background.png barr1.rgb concdal.rgb grass-aa.rgb \
			house.rgb poutre3_arbor_n.rgb roof1.rgb shadow2.rgb std.rgb texte1.png torcs1.rgb \
			town-border-arbor.png tr-asphalt-2-aa-r_n.png tr-asphalt-aa-bw1_n.rgb tr-building1.rgb \
			tr-building2.rgb tr-building3.rgb tr-building5.rgb tr-building6.rgb tr-building7.rgb \
			tr-building8.rgb tr-building9.rgb tr-curb-bw-aa-r.rgb tree-border_n.rgb treeg10_n.rgb \
			tree-new_n.rgb tree-poplar_n.rgb tr-house-arbor_n.png tr-house-arbor2_n.png tr-road1_n.rgb \
			tr-road1-pit_n.rgb tr-spec.png truck_arbor_ctd_n.rgb truck0.rgb walls.rgb walls2.rgb \
			readme.txt 

data-tracks-road_PKGFILES	= $(DATA)

data-tracks-road_PKGDIR	= $(DATADIR)

include ${MAKE_DEFAULT}


