##############################################################################
#
#    file                 : Makefile
#    created              : Sat Mai 20 17:12:55 CET 2006
#    copyright            : (C) 2006 by Bernhard Wymann
#    email                : berniw@bluewin.ch
#    version              : $Id: Makefile,v 1.1 2006/08/19 21:52:07 berniw Exp $
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################

TRACK     = ruudskogen

DATADIR   = tracks/road/$(TRACK)

DATA      = $(TRACK).xml $(TRACK).acc $(TRACK).png readme.txt background.png shadow2.rgb \
			env.png arb01_n.png arb02_n.png background.png dekk01.png grass01.png \
			grass02.png hus02.png hytte01.png lave01.png lave02.png rk_tree_1_n.png \
			rk_tree_2_n.png rk_tree_3_n.png road01-dashlines.png road01-pitentry.png \
			road01-pits_n.png road01.png road02.png road03.png road-edge.png \
			ruudskog_arbor.png sand01.png

data-tracks-road_PKGFILES	= $(DATA)

data-tracks-road_PKGDIR	= $(DATADIR)

include ${MAKE_DEFAULT}


