##############################################################################
#
#    file                 : Makefile
#    created              : Wed Jan 19 19:07:05 CET 2000
#    copyright            : (C) 1999-2005 by Eric Espie, Bernhard Wymann
#    email                : torcs@free.fr   
#    version              : $Id: Makefile,v 1.10 2005/07/07 13:57:30 berniw Exp $                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################


DATADIR   = tracks/road/g-track-1

DATA      = g-track-1.xml g-track-1.acc background.png  g-track-1.png readme.txt \
			asphalt-bw-g1-1_n.rgb asphalt-bw-g1-patch-1_n.rgb asphalt-bw-g1-patch-2_n.rgb \
			asphalt-bw-g1-patch-3_n.rgb asphalt-bw-g1-pit_n.rgb asphalt-bw-g1-pitentry-side_n.rgb \
			asphalt-bw-g1-pitentry_n.rgb asphalt-bw-g1-sidel-end_n.rgb asphalt-bw-g1-sidel-start_n.rgb \
			asphalt-bw-g1-sidel_n.rgb barr1.rgb earth_and_grass.rgb facade1-512.rgb facade6-512.rgb \
			facade7.rgb fence-arbor_n.rgb grass-g1.rgb poutre3_arbor_n.rgb poutre4.rgb roof1.rgb \
			roof3.rgb spectator.rgb std.rgb tarmac-wall-2-g2.rgb tent.rgb torcs0_arbor_n.rgb torcs1.rgb \
			tr-asphalt-aa-bw1_n.rgb tree53_n.rgb truck_arbor_berniw_n.rgb truck_arbor_bt_n.rgb \
			truck_arbor_inferno_n.rgb truck_arbor_speedy_n.rgb truck_arbor_tita_n.rgb wall-green-yellow.rgb \
			wall-grey.rgb wall4.rgb shadow2.rgb

data-tracks-road_PKGFILES	= $(DATA)

data-tracks-road_PKGDIR		= $(DATADIR)

include ${MAKE_DEFAULT}


