##############################################################################
#
#    file                 : Makefile
#    created              : Sun Feb 24 13:15:05 CET 2008
#    copyright            : (C) 2008 by Bernhard Wymann
#    email                : berniw@bluewin.ch
#    version              : $Id: Makefile,v 1.1 2008/02/24 12:55:08 berniw Exp $
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################

TRACK     = forza

DATADIR   = tracks/road/forza

DATA      = $(TRACK).xml $(TRACK).acc $(TRACK).png readme.txt \
			100.png 300.png ABtree_n.png background.png BAtree_n.png BEtree_n.png \
			BLBDBK.png BLDAB.png BLDA.png BLUPOLE.png BRtree_n.png BTOWB.png BUtree_n.png \
			CAtree_n.png CHtree_n.png CMNTA.png CMNTBB.png CMNTB.png conc.png CONCTP.png CRNA.png \
			CRNB.png CRNC.png CRND.png CRNF.png DBLOGO.png FERRED.png FLTBLK.png FNCEB.png forza.png \
			FRRI.png FRtree_n.png G2tree_n.png GBtree_n.png GCtree_n.png GDtree_n.png GEtree_n.png \
			GFtree_n.png GGtree.png GNtree_n.png GRAS2B.png GRtree_n.png GSBLUE.png GSBSTAIR.png \
			GSDH.png GSPAtree.png GSRNDF.png GSSOLID.png GStree_n.png GSUNDER.png ITtree_n.png \
			IYtree_n.png LIGHT.png LOGOAGIP.png LOGOBRDG.png LOGOBRDS.png LOGOCAMP.png LOGOCAST.png \
			LOGODTWO.png LOGOFOST.png LOGOFSTN.png LOGOITAL.png LOGOJOE.png LOGOMAG.png LOGOMBLO.png \
			LOGOSELE.png LOGOSHL.png MAGNMAR.png METALA.png PDtree_n.png PEtree_n.png PFtree_n.png \
			PITBLD.png PITLITE.png PITPPL.png PITWB.png POLEA.png POLLOL.png REF.png Road-crack1.png \
			Road-crack2.png ROADPGC.png ROADPL_n.png Road.png ROADSF_n.png RSA_n.png RSDOT_n.png \
			RSGRAS_n.png RS_n.png RSROAD_n.png RSSAGR_n.png RSSAND_n.png SAND_n.png SANDT_n.png \
			shadow2.png STAIRSD.png STAIRS.png STNDUND.png STNDUNDR.png TAGTNTOP.png TENTA.png \
			TENTD.png TENTG.png TENTH.png TEtree_n.png TIME1A.png TIME1B.png TIME2A.png TIME2B.png \
			TIME2C.png TIRE2.png TIRE3.png TIRE4A.png TIRE4.png TNTSHD.png TOPCROWD.png tree1_n.png \
			tree2_n.png tree3_n.png treefc_n.png treel1_n.png treel2_n.png treel3_n.png treel4_n.png \
			treetd_n.png TRETRNK.png TRKJUMA.png TRKJUMB.png TRKJUMC.png TRKJUM.png TURNA.png TURNB.png \
			WAtree_n.png WHEEL.png WIREWOOD.png

data-tracks-road_PKGFILES	= $(DATA)

data-tracks-road_PKGDIR	= $(DATADIR)

include ${MAKE_DEFAULT}


