##############################################################################
#
#    file                 : Makefile
#    created              : Wed Jan 19 19:07:05 CET 2000
#    copyright            : (C) 1999 by Eric Espie                         
#    email                : torcs@free.fr   
#    version              : $Id: Makefile,v 1.9 2004/11/06 15:01:22 torcs Exp $                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################


DATADIR   = tracks/dirt/dirt-4

DATA      = dirt-4.xml background.png dirt-4.ac dirt-4.png readme.txt

data-tracks-dirt_PKGFILES	= $(DATA)

data-tracks-dirt_PKGDIR	= $(DATADIR)

include ${MAKE_DEFAULT}


