##############################################################################
#
#    file                 : Makefile
#    created              : Wed Jan 19 19:07:05 CET 2000
#    copyright            : (C) 1999 by Eric Espie                         
#    email                : torcs@free.fr   
#    version              : $Id: Makefile,v 1.10 2005/03/10 13:43:51 berniw Exp $                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################


DATADIR   = tracks/road/eroad

DATA      = eroad.xml background.png eroad.acc eroad.png readme.txt tr-wall-torcs1-left.rgb \
			tr-wall-torcs1-right.rgb tr-asphalt-l2bw1_n.rgb shadow2.rgb \
			tr-asphalt-bw1-pits_n.rgb tr-asphalt-l2bw1-pe_n.rgb tr-asphalt-l2bw1-pl_n.rgb \
			tr-barrier-bw2.rgb

data-tracks-road_PKGFILES	= $(DATA)

data-tracks-road_PKGDIR		= $(DATADIR)

include ${MAKE_DEFAULT}


