##############################################################################
#
#    file                 : Makefile
#    created              : Sat Mai 20 17:12:55 CET 2006
#    copyright            : (C) 2008 by Bernhard Wymann
#    email                : berniw@bluewin.ch
#    version              : $Id: Makefile,v 1.1.2.1 2008/06/04 23:09:11 berniw Exp $
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################

TRACK     = alpine-2

DATADIR   = tracks/road/$(TRACK)

DATA      = $(TRACK).xml $(TRACK).acc $(TRACK).png readme.txt \
			arbor2_n.rgb concrete2.rgb shadow2.rgb tr-stone-wall.rgb truck_arbor_berniw_n.rgb \
			truck_arbor_dummy_n.rgb truck_arbor_hymie_n.rgb truck_arbor_inferno_n.rgb \
			truck_arbor_mouse_n.rgb truck_arbor_ole_n.rgb truck_arbor_speedy_n.rgb \
			truck_arbor_tp_n.rgb truck_arbor_usr_n.rgb alpine-2.png armco2_arbor.png \
			armco_snow_arbor.png armcoturn_arbor.png background.png BARS_tree_n.png BLBDBK.png \
			BLDG05_tree.png brick01.png cliff.png CMNTA.png concdark.png CONCRE.png \
			concrete01.png concwall2.png concwall.png GRDRA_tree_n.png ice.png LOGOMELA.png \
			LOGOMELC.png ppla_tree_n.png pplb_tree_n.png pplc_tree_n.png racelinedark2light.png \
			racelinedark.png racelinelight2dark.png racelinelight.png RAILtree_n.png \
			road2snow-edge.png road2snow.png road-line-edge.png road-lines2.png \
			road-linesbrleft.png road-linesbroken.png road-linesbrrightt.png road-pit.png \
			road.png road-snow.png rockwall2.png rockwall.png SEATS.png shadow2.png snow_2.png \
			snow_3.png snow_4.png snow.png steel01.png TOWER_tree_n.png tree1_n.png tree2_n.png \
			tree3_n.png tree6_n.png tree7_n.png tree8_n.png WALL.png

data-tracks-road_PKGFILES	= $(DATA)

data-tracks-road_PKGDIR	= $(DATADIR)

include ${MAKE_DEFAULT}


