##############################################################################
#
#    file                 : Makefile
#    created              : Sun Feb 13 17:46:19 CET 2000
#    copyright            : (C) 2000 by Eric Espie                         
#    email                : torcs@free.fr   
#    version              : $Id: Makefile,v 1.12 2004/11/06 15:01:23 torcs Exp $                                  
#
##############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
##############################################################################


DATADIR    = tracks/road/e-track-2

DATA   = e-track-2.xml e-track-2.acc background.png e-track-2.png env.png pylon3.rgb readme.txt

data-tracks-road_PKGFILES	= $(DATA)

data-tracks-road_PKGDIR	= $(DATADIR)

include ${MAKE_DEFAULT}



